version: "3"

services:
  db:
    image: mysql:8.0.36
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/api/
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql_data:
