version: "3"

services:
  db:
    image: mysql:8.0.36
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_vol:/var/lib/mysql

  api:
    build: .
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app/
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  redis: 
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/data


volumes:
  mysql_vol:
  redis_vol:
