user:
  name_max: 50
  email_max: 255
  password_min: 6
  password_max: 20
  email_format: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

token:
  access_token_exp: 4
  refresh_token_exp: 7

gg_oauth:
  userinfo_url: https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=
  token_url: https://accounts.google.com/o/oauth2/token
  allowed_email_domains:
    - 'sun-asterisk.com'

aws_s3:
  max_file_size: 50
  allowed_file_types: 
    - 'image/jpeg'
    - 'image/png'
    - 'image/gif'
    - 'video/mp4'
  url_expires_in: 3600